/** \file
  * \brief DB Constants
  * 
  * DB constants and translations, autogenerated from schema.sql 
  * by ./create-db-consts.pl */

// Qt
#include <QtGlobal>

// App
#include "db_consts.h"

// Values from schema.sql marked for translation
static const char * db_strings[] = {

    // state
     QT_TRANSLATE_NOOP("Item", "booked" )
    ,QT_TRANSLATE_NOOP("Item", "discarded" )
    ,QT_TRANSLATE_NOOP("Item", "in" )
    ,QT_TRANSLATE_NOOP("Item", "lost" )
    ,QT_TRANSLATE_NOOP("Item", "maintenance" )
    ,QT_TRANSLATE_NOOP("Item", "out" )

    // event
    ,QT_TRANSLATE_NOOP("Item", "booked" )
    ,QT_TRANSLATE_NOOP("Item", "created" )
    ,QT_TRANSLATE_NOOP("Item", "deleted" )
    ,QT_TRANSLATE_NOOP("Item", "discarded" )
    ,QT_TRANSLATE_NOOP("Item", "handed_out" )
    ,QT_TRANSLATE_NOOP("Item", "lost" )
    ,QT_TRANSLATE_NOOP("Item", "other" )
    ,QT_TRANSLATE_NOOP("Item", "returned" )
    ,QT_TRANSLATE_NOOP("Item", "sent_for_maintenance" )


};

// Const storage
const QString DB::Item::State::booked = "booked";
const QString DB::Item::State::discarded = "discarded";
const QString DB::Item::State::in = "in";
const QString DB::Item::State::lost = "lost";
const QString DB::Item::State::maintenance = "maintenance";
const QString DB::Item::State::out = "out";

const QString DB::Item::Event::booked = "booked";
const QString DB::Item::Event::created = "created";
const QString DB::Item::Event::deleted = "deleted";
const QString DB::Item::Event::discarded = "discarded";
const QString DB::Item::Event::handed_out = "handed_out";
const QString DB::Item::Event::lost = "lost";
const QString DB::Item::Event::other = "other";
const QString DB::Item::Event::returned = "returned";
const QString DB::Item::Event::sent_for_maintenance = "sent_for_maintenance";



