# To build if you do not have qtcreator

all:	runqmake updateschemas build unittest languages

runqmake:
	qmake

updateschemas:
	make -C schema

build:	updateschemas
	make -j4 

unittest:	build
	cd unittest && \
	./unittest-wrapper.sh

languages:  unittest
	make -f Makefile.l10n release
