//
// Snow Stuff For Hire - A POS-like system designed for very quick rental
// operations at small ski resorts
// Copyright (C) 2014 Mads Bondo Dydensborg <mads@dydensborg.dk>
//
// This file is part of Snow Stuff For Hire.
//
// Snow Stuff For Hire is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Snow Stuff For Hire is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Snow Stuff For Hire.  If not, see <http://www.gnu.org/licenses/>.
//

/** \file
  * \brief DB Constants
  * 
  * DB constants and translations, autogenerated from schema.sql 
  * by ./create-db-consts.pl */

// Qt
#include <QtGlobal>

// App
#include "db_consts.h"

// Values from schema.sql marked for translation
static const char * db_strings[] = {

    // state
     QT_TRANSLATE_NOOP("Item", "booked" )
    ,QT_TRANSLATE_NOOP("Item", "discarded" )
    ,QT_TRANSLATE_NOOP("Item", "in" )
    ,QT_TRANSLATE_NOOP("Item", "lost" )
    ,QT_TRANSLATE_NOOP("Item", "maintenance" )
    ,QT_TRANSLATE_NOOP("Item", "out" )

    // state
    ,QT_TRANSLATE_NOOP("Contract", "active" )
    ,QT_TRANSLATE_NOOP("Contract", "booking" )
    ,QT_TRANSLATE_NOOP("Contract", "closed" )
    ,QT_TRANSLATE_NOOP("Contract", "parked" )

    // state
    ,QT_TRANSLATE_NOOP("ContractItem", "booked" )
    ,QT_TRANSLATE_NOOP("ContractItem", "out" )
    ,QT_TRANSLATE_NOOP("ContractItem", "returned" )

    // event
    ,QT_TRANSLATE_NOOP("Item", "booked" )
    ,QT_TRANSLATE_NOOP("Item", "created" )
    ,QT_TRANSLATE_NOOP("Item", "deleted" )
    ,QT_TRANSLATE_NOOP("Item", "discarded" )
    ,QT_TRANSLATE_NOOP("Item", "handed out" )
    ,QT_TRANSLATE_NOOP("Item", "lost" )
    ,QT_TRANSLATE_NOOP("Item", "other" )
    ,QT_TRANSLATE_NOOP("Item", "reid" )
    ,QT_TRANSLATE_NOOP("Item", "returned" )
    ,QT_TRANSLATE_NOOP("Item", "sent for maintenance" )
    ,QT_TRANSLATE_NOOP("Item", "status" )


};

// Const storage
const QString DB::Item::State::booked = "booked";
const QString DB::Item::State::discarded = "discarded";
const QString DB::Item::State::in = "in";
const QString DB::Item::State::lost = "lost";
const QString DB::Item::State::maintenance = "maintenance";
const QString DB::Item::State::out = "out";

const QString DB::Contract::State::active = "active";
const QString DB::Contract::State::booking = "booking";
const QString DB::Contract::State::closed = "closed";
const QString DB::Contract::State::parked = "parked";

const QString DB::ContractItem::State::booked = "booked";
const QString DB::ContractItem::State::out = "out";
const QString DB::ContractItem::State::returned = "returned";

const QString DB::Item::Event::booked = "booked";
const QString DB::Item::Event::created = "created";
const QString DB::Item::Event::deleted = "deleted";
const QString DB::Item::Event::discarded = "discarded";
const QString DB::Item::Event::handed_out = "handed out";
const QString DB::Item::Event::lost = "lost";
const QString DB::Item::Event::other = "other";
const QString DB::Item::Event::reid = "reid";
const QString DB::Item::Event::returned = "returned";
const QString DB::Item::Event::sent_for_maintenance = "sent for maintenance";
const QString DB::Item::Event::status = "status";



